<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/bootstrap.php';
require_once __DIR__ . '/../config/database.php';
$id = incident_id($_GET['id'] ?? null);
try { $stmt = db()->prepare('SELECT * FROM incidents WHERE id = :id'); $stmt->execute(['id'=>$id]); $incident = $stmt->fetch(); }
catch (Throwable $exception) { error_log('View incident failed: ' . $exception->getMessage()); http_response_code(503); exit('Application temporarily unavailable.'); }
if (!$incident) { http_response_code(404); exit('Incident not found.'); }
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= escape($incident['title']) ?> · CloudOps</title><link rel="stylesheet" href="/assets/css/style.css"></head><body><header class="topbar"><div class="wrap"><a class="brand" href="/"><span class="brand-mark">C<span>+</span></span><span class="brand-copy"><strong>CloudOps</strong><small>INCIDENT TRACKER</small></span></a></div></header><main class="wrap narrow"><a class="back" href="/">← Dashboard</a><div class="page-head"><div><p class="eyebrow">INCIDENT #<?= $id ?></p><h1><?= escape($incident['title']) ?></h1></div><a class="button" href="/update.php?id=<?= $id ?>">Edit incident</a></div><section class="panel detail"><dl><div><dt>Service</dt><dd><?= escape($incident['affected_service']) ?></dd></div><div><dt>Severity</dt><dd><span class="badge severity-<?= strtolower($incident['severity']) ?>"><?= escape($incident['severity']) ?></span></dd></div><div><dt>Status</dt><dd><span class="badge status-<?= strtolower($incident['status']) ?>"><?= escape($incident['status']) ?></span></dd></div><div><dt>Created</dt><dd><?= escape($incident['created_at']) ?></dd></div><div><dt>Updated</dt><dd><?= escape($incident['updated_at']) ?></dd></div><div><dt>Resolved</dt><dd><?= escape($incident['resolved_at'] ?? '—') ?></dd></div></dl><h2>Description</h2><p class="prose"><?= nl2br(escape($incident['description'])) ?></p><h2>Resolution</h2><p class="prose"><?= $incident['resolution'] ? nl2br(escape($incident['resolution'])) : 'No resolution notes yet.' ?></p></section><form method="post" action="/delete.php" onsubmit="return confirm('Delete this incident?');"><input type="hidden" name="csrf_token" value="<?= escape(csrf_token()) ?>"><input type="hidden" name="id" value="<?= $id ?>"><button class="danger" type="submit">Delete incident</button></form></main></body></html>
